print("Input required data.")
name = input("Student name: ")
lab = int(input("Please enter the lab note: "))
midterm = int(input("Please enter the midterm score: "))
finals = int(input("Please enter the final score: "))
grade = (lab * 0.25) + (midterm * 0.35) + (finals * 0.4)
print("The information is as follows.")
print("Name:", name)
print("Lab score:", lab)
print("Midterm:", midterm)
print("Finals:", finals)
print("Grade score:", grade)